# Name of the workflow
name: Simple Workflow by Tony
# Trigger of the workflow
on:  
  push:
# Jobs in the workflow
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout the repostiory        
        uses: actions/checkout@v4      
      - name: Build the image        
        run: docker build -t neduru/sample-project:latest .     
      - name: List the built Docker image        
        run: docker image ls
